# Generated by Django 2.1.5 on 2019-02-08 21:49

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import reportious.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHoursReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('days', django.contrib.postgres.fields.jsonb.JSONField(validators=[reportious.validators.validate_report_working_days])),
                ('driving_in_km', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
